In [1]:
from transformers import T5Tokenizer, TFT5ForConditionalGeneration
import tensorflow as tf

In [2]:
model_name = 't5-small' 

In [3]:
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = TFT5ForConditionalGeneration.from_pretrained(model_name)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


All PyTorch model weights were used when initializing TFT5ForConditionalGeneration.

All the weights of TFT5ForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.


In [4]:
t5_input_text = "Translate English to German: Hello, how are you?"

In [5]:
tokenized_text = tokenizer(t5_input_text, return_tensors='tf', max_length=512, truncation=True)

In [6]:
print(tokenized_text)

{'input_ids': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=
array([[30355,    15,  1566,    12,  2968,    10,  8774,     6,   149,
           33,    25,    58,     1]])>, 'attention_mask': <tf.Tensor: shape=(1, 13), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])>}


In [7]:
output = model.generate(tokenized_text['input_ids'])

D:\New folder\anaconda\Lib\site-packages\transformers\generation\tf_utils.py:837: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length.  recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


In [8]:
decoded_output = tokenizer.decode(output[0], skip_special_tokens=True)

In [9]:
print("Generated Translation:", decoded_output)

Generated Translation: Hallo, wie sind Sie?
